
//Innerhtml

//text.innerHTML = "This is generated by an Inner HTML";

//creating a HTML element in JS

const bold = document.createElement("strong");
bold.innerText = "THIS IS H2 ELEMENT CREATED USING JAVASCRIPT";
body.append(bold);

//Removing an element from the HTML
// addTaskBtn.remove();
// body.append(addTaskBtn);

//Styles in JS
//addTaskBtn.style.backgroundColor = 'red'